title: Vertical
author: Twinkle
description: Another simple hexo theme
date_format: MM-DD HH:mm

menu:
  首页: /
  关于: /about

social:
  github: saintwinkle
  weibo: 天然傲娇 #这里填写昵称即可
  v2ex: 
  twitter: 
  google_plus: 
